### ISSUE TITLE
Don't provide feedback for locked abilities

### ISSUE THREAD

**Issue by Sheemap** [xivanalysis/xivanalysis#1186]
Hey all,

Would it be possible/reasonable to avoid suggesting feedback for locked abilities? Im relatively new to the game, and only level 60 AST. Importing my logs into the site doesn't work well because I don't have all abilities unlocked, such as sleeve draw. I think it could be useful to avoid suggesting feedback for abilities like that, and readjust the calculations to take into account those missing abilities

I understand this tool is mainly for end game content, and making sure you play well there, but it would be nice to be able to learn to optimize as we are leveling up classes, get us more prepared for when we actually reach end game.

Could this be possible by detecting player/encounter level? Im not sure the data available to make that decision, or how much work is actually involved for this. Id be willing to work on this feature if someone could point me in the right direction though.

Lemme know what you all think about this! Thanks

**Comment by ayyaruq** [comment]
We only officially support max level. When it comes to getting real level (and levelsync status), the data is in ACT logs but hidden by fflogs again. The way our action/status/logic data is structured, we can't adjust the way skills change with traits since there's no way to map traits from fflogs data. We can handle patch changes, to a degree, but not much beyond that. Some stuff could probably be detected with heuristics but not everything. Essentially it comes down to lack of data, and a little bit of the way we've structured things. Feel free to swing by our discord server if you want to try figure out a way to do it though.
