### ISSUE TITLE
 FFLogs Effect event encountered with no packet ID, did not match to over time status effect (DoT/HoT)

### ISSUE THREAD

**Issue by EnderByEndera** [xivanalysis/xivanalysis#1223]
I've met the above error when analysing my own fflogs about the **unfinished Titan(Unreal) Trial** and clicked one of the characters. After some time passed, I met this error and I don't know the reason. 
Web browser: Microsoft Edge with Chromium 92.0.902.67
fflogs: https://cn.fflogs.com/reports/WVzb2nJhwGc9KdfY/#fight=8

**Comment by ayyaruq** [comment]
Apologies for the delay, this error message happens when the log is missing a sequence ID, which we use to link actions to their effects, and has no status ID. Damage/Heal over Time events don't have the sequence ID, but the error means that the event doesn't match any known statuses to tell us what it is. Usually this happens when the log has bad data, which can happen with a network fault, memory misread, or in fflogs' parsing of it.
