### ISSUE TITLE
Gaps between Holy Spirit and Confiteor trick PLD analysis

### ISSUE THREAD

**Issue by wesleywright** [xivanalysis/xivanalysis#1508]
Expected: confiteor usage gets matched to holy spirits as long as they are in the same requiescat window

Actual: a gap of several GCDs between last Holy Spirit and a Confiteor is treated as two separate requiescat windows

here’s my analysis showing the behavior: https://xivanalysis.com/fflogs/PNaZ6VyxWBAGfQ9X/1/5

![749AD786-D881-4F79-B740-DC4B46968BD0](https://user-images.githubusercontent.com/4690880/148075896-3bda4a9c-dd58-4ead-8d5c-f9caba8d65d5.jpeg)

**Comment by Ansatusya** [comment]
I think it's working as expected. 

Let me detail my thoughts : 

Looking at the timeline 8:06 is the time at which you got requiescat buff, the first Holy Spirit comes in at 8:29 and the fourth one at 8:36, and you're losing resquiescat due to the 30 seconds buff duration thus ending the first window.

While confiteor come, still according to timeline, at around 9:14 and the resquiescat opening this window is weaved at 9:12.

Unless I'm missing your point they are indeed two differents windows.

**Comment by wesleywright** [comment]
Ah, that’s my bad — I know I had at least one pull where I mixed in melee before confiteor, but clearly not this one (not that either is a good habit either way, haha). Closing.
