### ISSUE TITLE
[WAR} Raw Intuition instead of Bloodwhetting for under 82 content

### ISSUE THREAD

**Issue by Zeal0us** [xivanalysis/xivanalysis#1937]
Warrior on 80 or lower content shows Bloodwhetting instead of Raw Intuition.  Specifically noticed this when checking UWU logs - shows 0 usages of Bloodwhetting when should probably be tracking Raw Intuition at that level. 

Admittedly, I rarely use xivanalysis on synced content so I'm not sure if this is expected behavior/wontfix.

**Comment by AzariahAeroborn** [comment]
We only support maximum level content.  While most jobs will include the lower level skills' data so that the lower level skills will show on the timeline, we don't adjust analysis for lower level skills or rotations, because many jobs have significant differences in their rotations and as such we don't support maintaining multiple sets of analysis per job.

**Comment by Zeal0us** [comment]
Gotcha, Closing.
