### ISSUE TITLE
[VPR] Don't penalise missing usages of legacy when it's not unlocked yet

### ISSUE THREAD

**Issue by jasperfirecai2** [xivanalysis/xivanalysis#2073]
![image](https://github.com/user-attachments/assets/cd0a0add-9648-4b4c-a16c-a3e3dd873ade)
![image](https://github.com/user-attachments/assets/c385553c-2343-45a5-9c2b-f6ba719bfba5)
Legacy is only unlocked at lvl 100, but it's docking tons of points for serpents tail usages at a lvl 96 dungeon

**Comment by Rjb99** [comment]
Viper's XIVA Analysis is not designed for leveling review, all modules assume that you are level 100.

I have no plans to support Viper outside of level 100 at this time.

**Comment by jasperfirecai2** [comment]
Can XIVanalysis support classes at different levels? e.g. for ultimates? cause i'll happily do PR then. if not, why?

**Comment by AzariahAeroborn** [comment]
> Can XIVanalysis support classes at different levels? e.g. for ultimates? cause i'll happily do PR then. if not, why?

Our support policy is and has been to only support analysis for max level content.  While we have recently been able to add an indicator in the About section for what level the log was recorded at, we are still not supporting analysis for sub-max level content at this time.  Ultimately, many jobs wind up being significantly different at lower levels to the point where you're effectively supporting an entirely separate job, and our volunteer resources for job maintenance are limited.

As an aside, ultimates often break additional principles of job analysis beyond just the level sync due to their fight design (multiple separate phases with their own DPS checks, separated by long downtimes, and timing of mechanics during uptime phases that often necessitates different play than using burst on cooldown).  So even were we to have analysis for level synced content, it would likely be of limited usefulness for ultimates.

**Comment by jasperfirecai2** [comment]
I understand the workload and nuance make it not realistic. I will close the issue. I think having a conditional load of modules and skills based on encounter level could be cool. And slightly increase the usability on synced content. But certainly not a priority, and not in the scope of this issue. Thank you for the detailed answer.
