### ISSUE TITLE
Incorrect weaving issue when using Subtractive Palette casts 

### ISSUE THREAD

**Issue by Secrean** [xivanalysis/xivanalysis#2109]
![image](https://github.com/user-attachments/assets/8d15f405-b742-4b7a-91cb-aa356ef75198)

**Comment by Secrean** [comment]
It's only for Pictomancer casts under Subtractive Palette, as they're 3.30s GCD

**Comment by AkairyuGestalter** [comment]
Given the timestamps in that screenshot, those weaving problems all appear to have occurred while Hyperphantasia was active from your Starry Muse. That trims the normal 1 second weave window after the Subtractive hardcast spells to .75s, which is all but guaranteed to clip if your ping isn't "living in the data center" levels of good. This is actually accurate and not a bug. You should try to weave after, Comet, your Hammers, or Star Prism, rather than the hardcasts.

**Comment by Secrean** [comment]
Know what, I've missed that and I'll be sure to weave properly from here on.
I still think there's something weird here, since if I truly would've missed a total of 5 seconds between GCDs in my 8 minute window, I wouldn't be able to fit all the recommended actions into the Starry Muse window, but I'm getting all of it in there.
Here's the [link](https://xivanalysis.com/fflogs/gvmBdptP3Lk91MrR/6/2) where you can see it. I think even a bad weave wouldn't be more than 2s at most if you properly mash the button for the next GCD.
