### ISSUE TITLE
chinese interface & display of buffs from self in timeline is wanted

### ISSUE THREAD

**Issue by ldiniiy** [xivanalysis/xivanalysis#317]
I can help translate but I don't know how to start. 

In addition, I think it would be better if buffs from self can be shown in the timeline, such as straight shot buff of the bard.

**Comment by MikeMatrix** [comment]
As for the buffs in timeline, that's definitely a valid point and I'm sure we'll implement it in the near future, although since it's very job dependent, it might be implemented to some, but not others for a bit.

As for the chinese translation (i18n), we would love to support more languages, but as it stands the chinese client is a few patches behind and we don't have ready translations available from the extracted client data on [xivdb](https://xivdb.com). As it stands, we're have very little translated in the 4 main client languages (Japanese, English, German and French) and those are our priority for now. Once we have a close to 100% translation on those, we'd definitely look into supporting other languages.

**Comment by ayyaruq** [comment]
@ldiniiy now that Crowdin works and the majority of the interface is translated for Chinese, is this still an issue? Re self buffs, most show up already, I've updated Straight Shot Ready in PR #824.
