### ISSUE TITLE
won't get combo during "meikyo shisui"

### ISSUE THREAD

**Issue by Yu-Hoto** [xivanalysis/xivanalysis#455]
Title.

example timeline:
Meikyo Shisui
→Yukikaze
→Kasha
→Midare Setsugekka
→Kaeshi: Setsugekka
→Hakaze
→Shifu(not combo)
→Kasha(not combo)

Shifu and Kasha are actually combos.
However, it is not possible on the ⅩⅣanalysis.

I'm sorry I'm not good at English.

**Comment by AzariahAeroborn** [comment]
Do you have an example of a log that is showing this issue?

**Comment by Rjb99** [comment]
No, It does combo in-game. the current logic for meikyo on our end is to just disable combos from being formed because all skills minus hakaze (which is the starting skill for all combos) can not be comboed from after the effect wears off.

I can look into making an exception for hakaze. But the current use case for proper meikyo is to do only sen granting moves (yuki/gekko/kasha) under it. so this really should be a non-issue outside of colossal mistakes.

**Comment by Yu-Hoto** [comment]
This issue is not big.

However, although you have won combos in the game, it is confusing when it is displayed as combo issue in xivanalytics.

It may be appropriate to prompt the user to use only sen acquisition (yukikaze / gekko / kasha) during meikyo effects rather than combo issues.

In addition, I think that it may be considered to leave this issue for other updates.

[example log](https://xivanalysis.com/analyse/t3X1F9M4gcVfLCTh/19/258/)

**Comment by ackwell** [comment]
Fixed in #490
