### ISSUE TITLE
Track Asylum usage

### ISSUE THREAD

**Issue by nivthefox** [xivanalysis/xivanalysis#599]
- [ ] Track the amount of possible uses in a fight (n).
- [ ] n-2 = green
- [ ] n-3 = yellow
- [ ] otherwise red
- [ ] Also ensure that it actually heals at least X% of the raid for X ticks.

**Comment by SaltedyLevity** [comment]
Same concern as the temperance one, I'm worried n-4 might be a little too forgiving? 

As for the healing amount done, I think it would be great to flag it if it does something like more than 45% overheal?
But it's also possible in a fight that everyone is spread out in that it's OK to use it on say, just a tank for autos - O10s (midgar) was an example. Not sure if this is worth incorporating or if it's too niche (or if it's something you'd just add a fight specific note for)

**Comment by kkragenbrink** [comment]
Updated to n-3 for yellow.  I ... feel like the one-person use is a niche, but I will think on it some.  Asylum overhealing, though, is going to happen regularly, isn't it? I am not sure I feel comfortable warning about Asylum overheal _specifically_.  We do already have a general overheal module which is in use.  Can you provide some more context on why that'd be a good idea?

**Comment by SaltedyLevity** [comment]
Hm, this might be me coming from a position of doing balance or DM'd log reviews all the time, and I see high overheal on this often which is usually a flag that it's not being planned with their co-healer and either the whm or the CO is healing on top of it unnecessarily, or stacking other HoTs like med2/WD when it's not needed. And since asylum is an oGCD, should be getting higher priority to heal with over a GCD heal (I don't think the overheal module breaks down skill specific, just hot, not hot, and total, right?)

So I guess my thinking is, when I see someone with 50% or 60% overheal on the bubble, they probably could've done something a lot better to avoid that and be more efficient with it.

Maybe the note here is to expand on the overheal module with what's doing silly amounts of overheal and is wasted? Not sure if that's too much information for users though.
