### ISSUE TITLE
Track Thin Air usage

### ISSUE THREAD

**Issue by nivthefox** [xivanalysis/xivanalysis#600]
- [ ] Track where the highest MP spells are cast, and suggest that Thin Air be used there. 
- [ ] This should be a suggestions module, not a warning module, especially if the WHM isn't running OOM.

**Comment by SaltedyLevity** [comment]
This looks accurate!

I don't know if this is helpful because I'm really not knowledgeable on how XIVA operates, but where my head is going: Thin air lasts 12s, but only snapshots at the end of a cast (so if it wears off before the cast is finished, you lose mp), and I've seen GCD estimates in XIVA be a bit inaccurate, so for the sake of looking for mp saving windows, you may want to check mp spent across a 10s window (maybe 9.5s?) to account for what was actually possible to save, rather than across 10.
(You were probably going to do something like this already maybe? Figured I'd spill my thoughts)

Then the wording could be something like "you could have possibly saved at least x amount of mp by using thin air at #:##" or however you intended to state it. So the "at least" covers the fact that you might've saved even more?

(Let me know if this doesn't make sense!)

**Comment by kkragenbrink** [comment]
Makes perfect sense. :) I'll have to see what I can do with it!

**Comment by IsaacKhor** [comment]
The idea sounds good, but there are a few issues when we dive into the details of how one would actually implement it.

We can calculate the usages of thin air that would maximise mana saved given the entire timeline of casts in the fight. This would produce something like 'use thin air at :30, 2:50, 5:20 to save 7200 mp; you used at xx:xx, yy:yy, and zz:zz, saving 6000 mp instead'. This is *sorta* helpful, in the sense that if you could travel back in time and reoptimise your thin air usages that's what you should do, but not very helpful in determining "that's what you should do the next time you run this fight". The target audience are people trying to improve their gameplay, not "I've spreadsheeted every gcd" player.

This is why I'm resistant to recommendations of 'use thin air at xx:xx', since it's so fight specific. I'm thinking a better implementation would be 'you rezzed at 1:30 without thin air even thought it was available', but that still runs into the issue of maybe you had planned on using it later in the fight for a cure3 spam (*cries in terminal*). 

All that is to say I'm not sure what's a good approach here. I think the 'you rezzed without thin air' is a good baseline, but anything more starts running into issues I've outlined above.

**Comment by ayyaruq** [comment]
Closing as no longer relevant in Endwalker.
