### ISSUE TITLE
Track Presence of Mind usage

### ISSUE THREAD

**Issue by nivthefox** [xivanalysis/xivanalysis#601]
- [ ] Track number of possible uses in a fight (n).
- [ ] n-1 = green
- [ ] n-2 = yellow
- [ ] otherwise red
- [ ] Possibly ensure it is mostly used for damage?

**Comment by SaltedyLevity** [comment]
This one I would just say n-1 = yellow, n-2+ = red. It's basically a DPS buff, and I think the cases where someone might lose an entire use due to fight downtime are much more niche than is worth the detriment to the player not knowing they missed one. 

You don't need to track if it's used mostly for damage, since at its heart all PoM does is increase your number of casts over a fight; whether you cast a heal under PoM or after PoM won't change your total casts in a fight. And it's CD is dumb, so it doesn't naturally align with anything.
That said, super optimized will hold it for some raid buff windows, maybe (in which case getting it on most damage casts is important) - but I don't think it's worth investing in the logic for this because it doesn't apply consistently in a fight and it varies heavily on kill time and your average player won't know theirs, and still requires making sure you don't lose a use. I can elaborate with some examples of when/where you'd align for raid buffs if you want to explore it further, though!

**Comment by AzariahAeroborn** [comment]
I think it would be simplest to track this as a CooldownDowntime tracked cooldown, similar to SCH & Chain Stratagem. Potentially Assize could also be collapsed into base oGCD tracking as well, since it isn’t dealing with any special handling either and it’s generally considered better to use assize for damage & mp rather than to hold for healing.
