### ISSUE TITLE
BuffWindows array of BadActions for explicit Suggestions

### ISSUE THREAD

**Issue by ayyaruq** [xivanalysis/xivanalysis#679]
BadActions currently takes an object with a Suggestion and list of Actions, but sometimes there's a need for separate Suggestions. In my case, it's 6SS needing separate text to Form Shift and Meditation. I'm proposing an array of objects to allow for them to have separate Suggestion texts.

**Comment by ayyaruq** [comment]
Prob relevant to @AzariahAeroborn.

**Comment by AzariahAeroborn** [comment]
Per our conversation on Discord - this was an intentional design choice to limit the core BuffWindow implementation to emitting a single suggestion for all BadActions.  If this is absolutely required for a certain job or specific skills, the implementing job can potentially override output/onComplete or add an additional complete hook that will add the extra suggestion, but we do not want to get suggestion bloat out of the core module.
